pip install numpy==1.23.0
pip install opencv-python
pip install torchgeometry
pip install transforms3d
pip install pycocotools
pip install smplx
pip install tqdm
pip install tensorboardX
pip install easydict
pip install pyyaml
pip install matplotlib
pip install scipy==1.5.4
pip install imageio
pip install scikit-image
pip install trimesh
pip install pyrender
pip install chumpy
pip install termcolor
pip install imageio[ffmpeg]
pip install json_tricks
conda install ffmpeg==4.3 -y